#' @title Loads pre-computed MCMC chains generated by the \code{BASiCS_MCMC} function
#'
#' @description  Loads pre-computed MCMC chains generated by the \code{BASiCS_MCMC} function, creating
#' a \code{\link[BASiCS]{BASiCS_Chain-class}} object
#'
#' @param RunName String used to index `.Rds` files storing the MCMC chains (produced by the \code{BASiCS_MCMC} function)
#' @param StoreDir Directory where `.Rds` files is stored. Default: \code{StoreDir = getwd()}
#'
#' @return An object of class \code{\link[BASiCS]{BASiCS_Chain-class}}.
#'
#' @examples
#'
#' Data = makeExampleBASiCS_Data()
#' Chain <- BASiCS_MCMC(Data, N = 50, Thin = 5, Burn = 5,
#'                            StoreChains = TRUE, StoreDir = tempdir(), 
#'                            RunName = "Test")
#' ChainLoad <- BASiCS_LoadChain(RunName = "Test", StoreDir = tempdir())
#'
#' @seealso \code{\link[BASiCS]{BASiCS_Chain-class}}
#'
#' @author Catalina A. Vallejos \email{cnvallej@@uc.cl}
#'
#' @references Vallejos, Marioni and Richardson (2015). Bayesian Analysis of Single-Cell Sequencing data.
BASiCS_LoadChain <- function(RunName, StoreDir = getwd())
{
  Chain <- readRDS(file.path(StoreDir, paste0("chain_", RunName, ".Rds")))
  return(Chain)
}