#' @title Loads pre-computed MCMC chains generated by the \code{BASiCS_MCMC} function
#'
#' @description  Loads pre-computed MCMC chains generated by the \code{BASiCS_MCMC} function, creating
#' a \code{\link[BASiCS]{BASiCS_Chain-class}} object
#'
#' @param RunName String used to index `.txt` files storing chains (as in \code{BASiCS_MCMC} function)
#' @param StoreDir Directory where `.txt` files are stored. Default: \code{StoreDir = getwd()}
#' @param WithSpikes \code{TRUE}/\code{FALSE} indicator of spike-ins usage. Default: \code{WithSpikes = TRUE}
#'
#' @return An object of class \code{\link[BASiCS]{BASiCS_Chain-class}}.
#'
#' @examples
#'
#' Data = makeExampleBASiCS_Data()
#' MCMC_Output <- BASiCS_MCMC(Data, N = 50, Thin = 5, Burn = 5,
#'                            StoreChains = TRUE, StoreDir = getwd(), RunName = "Test")
#' MCMC_Output_Load <- BASiCS_LoadChain(RunName = "Test", StoreDir = getwd())
#'
#' @seealso \code{\link[BASiCS]{BASiCS_Chain-class}}
#'
#' @author Catalina A. Vallejos \email{cnvallej@@uc.cl}
#'
#' @references Vallejos, Marioni and Richardson (2015). Bayesian Analysis of Single-Cell Sequencing data.
BASiCS_LoadChain <- function(RunName, StoreDir = getwd(), WithSpikes = TRUE)
{
  ChainMu = as.matrix(fread(file.path(StoreDir, paste0("chain_mu_", RunName, ".txt"))))
  ChainDelta = as.matrix(fread(file.path(StoreDir, paste0("chain_delta_", RunName, ".txt"))))
  ChainPhi = as.matrix(fread(file.path(StoreDir, paste0("chain_phi_", RunName, ".txt"))))
  # Add-hoc fix for the no-spikes case
  if(WithSpikes == TRUE) {ChainS = as.matrix(fread(file.path(StoreDir, paste0("chain_s_", RunName, ".txt"))))}
  else {ChainS = matrix(1, ncol = ncol(ChainPhi), nrow = nrow(ChainPhi))}
  ChainNu = as.matrix(fread(file.path(StoreDir, paste0("chain_nu_", RunName, ".txt"))))
  ChainTheta = as.matrix(fread(file.path(StoreDir, paste0("chain_theta_", RunName, ".txt"))))
  
  MCMC_Output = newBASiCS_Chain(mu = ChainMu, 
                                delta = ChainDelta, 
                                phi = ChainPhi, 
                                s = ChainS, 
                                nu = ChainNu, 
                                theta = ChainTheta) 
  
  return(MCMC_Output)
  
}