#' @title Loads pre-computed MCMC chains generated by the 
#' \code{\link[BASiCS]{BASiCS_MCMC}} function
#'
#' @description  Loads pre-computed MCMC chains generated by the 
#' \code{\link[BASiCS]{BASiCS_MCMC}} function, creating
#' a \code{\link[BASiCS]{BASiCS_Chain}} object
#'
#' @param RunName String used to index `.Rds` file containing the MCMC chain (produced by the 
#' \code{\link[BASiCS]{BASiCS_MCMC}} function, with \code{StoreChains = TRUE})
#' @param StoreDir Directory where `.Rds` file is stored. Default: \code{StoreDir = getwd()}
#'
#' @return An object of class \code{\link[BASiCS]{BASiCS_Chain}}.
#'
#' @examples
#'
#' Data = makeExampleBASiCS_Data()
#' Chain <- BASiCS_MCMC(Data, N = 50, Thin = 5, Burn = 5,
#'                            StoreChains = TRUE, StoreDir = tempdir(), 
#'                            RunName = 'Test')
#' ChainLoad <- BASiCS_LoadChain(RunName = 'Test', StoreDir = tempdir())
#'
#' @seealso \code{\link[BASiCS]{BASiCS_Chain}}
#'
#' @author Catalina A. Vallejos \email{cnvallej@@uc.cl}, Nils Eling
#'
#' @references 
#' Vallejos, Marioni and Richardson (2015). PLoS Computational Biology. 
BASiCS_LoadChain <- function(RunName, StoreDir = getwd()) {
    Chain <- readRDS(file.path(StoreDir, paste0("chain_", RunName, ".Rds")))
    return(Chain)
}
