#' @name BASiCS_Chain
#' @aliases BASiCS_Chain-class
#' 
#' @title The BASiCS_Chain class
#' 
#' @description Container of an MCMC sample of the BASiCS' model parameters 
#' (see Vallejos et al, 2015) as generated by the 
#' function \code{\link[BASiCS]{BASiCS_MCMC}}. 
#' @slot parameters List of matrices containing MCMC chains for each model parameter. Depending on the mode in which 
#' BASiCS was run, the following parameters can appear in the list:
#' \describe{
#' \item{\code{mu}}{MCMC chain for gene-specific mean expression parameters 
#' \eqn{\mu_i}, biological genes only 
#' (matrix with \code{q.bio} columns, all elements must be positive numbers)}
#' \item{\code{delta}}{MCMC chain for gene-specific biological cell-to-cell heterogeneity hyper-parameters \eqn{\delta[i]}, biological genes only 
#' (matrix with \code{q.bio} columns, all elements must be positive numbers)}
#' \item{\code{phi}}{MCMC chain for cell-specific mRNA content normalising constants \eqn{\phi[j]}
#' (matrix with \code{n} columns, all elements must be positive numbers and the sum of its elements must be equal to \code{n})}
#' \item{\code{s}}{MCMC chain for cell-specific capture efficiency (or amplification biases if not using UMI based counts) normalising constants \eqn{s[j]}
#' (matrix with \code{n} columns, all elements must be positive numbers)}
#' \item{\code{nu}}{MCMC chain for cell-specific random effects \eqn{\nu[j]}
#' (matrix with \code{n} columns, all elements must be positive numbers)}
#' \item{\code{theta}}{MCMC chain for technical variability hyper-parameter(s) \eqn{\theta} (matrix, all elements must be positive, each colum 
#' represents 1 batch)}
#' \item{\code{beta}}{MCMC chain for regression parameters
#' (matrix with \code{k} columns where k represent the number of chosen basis functions) }
#' \item{\code{sigma2}}{MCMC chain for the variance used during regression
#' (matrix with one column, sigma2 represents a gloabl parameter)}
#' \item{\code{eta}}{MCMC chain for the degrees of freedom used for regression
#' (matrix with one column)}
#' \item{\code{lambda}}{MCMC chain for the gene-specific random effect on the regression variance
#' (matrix with \code{q} columns)}
#' \item{\code{epsilon}}{MCMC chain for the gene specific regression residue (mean corrected vraribility)
#' (matrix with \code{q} columns)}
#' }
#' @examples
#' 
#' # A BASiCS_Chain object created by the BASiCS_MCMC function.
#' Data = makeExampleBASiCS_Data()
#' MCMC_Output <- BASiCS_MCMC(Data, N = 100, Thin = 2, Burn = 2)
#' 
#' # To run the model using the regession (mean adjustment of the over-dispersion parameters) use following function:
#' MCMC_Output_Reg <- BASiCS_MCMC(Data, N = 100, Thin = 2, Burn = 2, Regression = TRUE, k = 12)
#' 
#' @author Catalina A. Vallejos \email{cnvallej@@uc.cl}, Nils Eling \email{eling@@ebi.ac.uk}
#' 
#' @references 
#' 
#' Vallejos, Marioni and Richardson (2015). PLoS Computational Biology.
#' 
setClass("BASiCS_Chain", 
         representation = representation(
           parameters = "list"), 
         contains="Versioned",
         validity = function(object) 
         {
            errors <- character()
            
            if (length(object@parameters$mu) == 0 | length(object@parameters$delta) == 0 | 
                length(object@parameters$phi) == 0 | length(object@parameters$s) == 0 | 
                length(object@parameters$nu) ==  0 | length(object@parameters$theta) == 0) 
            {
              errors <- c(errors, "One or more of the parameters mu, delta, phi, s, nu are missing")
              return(errors)
            }
    
          N <- nrow(object@parameters$mu)
          n <- ncol(object@parameters$phi)
          if (nrow(object@parameters$delta) != N | nrow(object@parameters$phi) != N | 
              nrow(object@parameters$s) != N | nrow(object@parameters$nu) != N | 
              nrow(object@parameters$theta) != N | 
              ncol(object@parameters$mu) != ncol(object@parameters$delta) | 
              ncol(object@parameters$s) != n | ncol(object@parameters$nu) != n) 
          {
            errors <- c(errors, "Slots' dimensions are not compatible")
          }
    
          if (sum(!is.finite(object@parameters$mu)) + sum(!is.finite(object@parameters$delta)) + 
              sum(!is.finite(object@parameters$phi)) + sum(!is.finite(object@parameters$s)) + 
              sum(!is.finite(object@parameters$nu)) + sum(!is.finite(object@parameters$theta))) 
          {
            errors <- c(errors, "Some of the slots mu, delta, phi, s or nu contains NAs or Infinite values")
          }
    
        if (length(errors) == 0) 
          TRUE else errors
      },
      prototype = prototype(new("Versioned",
                                versions = c("BASiCS_Chain" = "0.99.8")))
      )


#' @name BASiCS_Summary
#' @aliases BASiCS_Summary-class
#' 
#' @title The BASiCS_Summary class
#' 
#' @description Container of a summary of a \code{\linkS4class{BASiCS_Chain}} 
#' object. In each slot, first column contains posterior medians; second and 
#' third columns respectively contain the lower and upper limits of an high 
#' posterior density interval (for a given probability).
#' 
#' @slot parameters List of parameters in which each entry contains a matrix: first column contains posterior medians, second column contains the lower limits of an high posterior
#' density interval and third column contains the upper limits of high posterior density intervals. List can contain:
#' \describe{
#' \item{\code{mu}}{Posterior medians (1st column), lower (2nd column) and upper 
#' (3rd column) limits of gene-specific mean expression parameters \eqn{\mu_i}.}
#' \item{\code{delta}}{Posterior medians (1st column), lower (2nd column) and upper 
#' (3rd column) limits of gene-specific biological over-dispersion parameters 
#' \eqn{\delta_i}, biological genes only }
#' \item{\code{phi}}{Posterior medians (1st column), lower (2nd column) and upper 
#' (3rd column) limits of cell-specific mRNA content normalisation 
#' parameters \eqn{\phi_j}}
#' \item{\code{s}}{Posterior medians (1st column), lower (2nd column) and upper 
#' (3rd column) limits of cell-specific technical normalisation 
#' parameters \eqn{s[j]}}
#' \item{\code{nu}}{Posterior medians (1st column), lower (2nd column) and upper 
#' (3rd column) limits of cell-specific random effects \eqn{\nu_j}}
#' \item{\code{theta}}{Posterior median (1st column), lower (2nd column) and upper 
#' (3rd column) limits of technical over-dispersion parameter(s) \eqn{\theta} 
#' (each row represents one batch)}
#' \item{\code{beta}}{Posterior median (first column), lower (second column) and upper (third column) limits of regression parameters \eqn{\beta}}
#' \item{\code{sigma2}}{Posterior median (first column), lower (second column) and upper (third column) limits of regression variance \eqn{\sigma^2}}
#' \item{\code{eta}}{Posterior median (first column), lower (second column) and upper (third column) limits of hype-parameter \eqn{\eta} for random effect on regression variance}
#' \item{\code{lambda}}{Posterior median (first column), lower (second column) and upper (third column) limits of random effect \eqn{\lambda} on regression variance}
#' \item{\code{epsilon}}{Posterior median (first column), lower (second column) and upper (third column) limits of regression residue \eqn{\epsilon} (mean adjusted over-dispersion)}
#' }
#' @examples
#' 
#' # A BASiCS_Summary object created by the Summary method.
#' Data = makeExampleBASiCS_Data()
#' Chain <- BASiCS_MCMC(Data, N = 100, Thin = 2, Burn = 2)
#' ChainSummary <- Summary(Chain)
#' 
#' 
setClass("BASiCS_Summary",
         representation = representation(
           parameters = "list"
         ),
         contains="Versioned",
         validity = function(object){
           if(sum(!(c("mu", "delta", "phi", "s", "nu") %in% names(object@parameters)))) {stop("One or more of the parameters: mu, delta, phi, s, nu are missing.")}
         },
         prototype = prototype(new("Versioned",
                                   versions = c("BASiCS_Summary" = "0.99.8")))
)
