#' @name BASiCS_Chain
#' @aliases BASiCS_Chain-class
#' 
#' @title The BASiCS_Chain class
#' 
#' @description Container of an MCMC sample of the BASiCS' model parameters 
#' (see Vallejos et al, 2015) as generated by the 
#' function \code{\link[BASiCS]{BASiCS_MCMC}}. 
#' 
#' @slot mu MCMC chain for gene-specific mean expression parameters 
#' \eqn{\mu_i}, biological genes only 
#' (matrix with \code{q.bio} columns, all elements must be positive numbers)
#' @slot delta MCMC chain for gene-specific biological over-dispersion 
#' parameters \eqn{\delta_i}, biological genes only 
#' (matrix with \code{q.bio} columns, all elements must be positive numbers)
#' @slot phi MCMC chain for cell-specific mRNA content normalisation parameters 
#' \eqn{\phi_j} (matrix with \code{n} columns, all elements must be positive 
#' numbers and the sum of its elements must be equal to \code{n})
#' @slot s MCMC chain for cell-specific technical normalisation parameters 
#' \eqn{s_j} (matrix with \code{n} columns, 
#' all elements must be positive numbers)
#' @slot nu MCMC chain for cell-specific random effects \eqn{\nu_j}
#' (matrix with \code{n} columns, all elements must be positive numbers)
#' @slot theta MCMC chain for technical over-dispersion parameter(s) 
#' \eqn{\theta} (matrix, all elements must be positive, 
#' each colum represents 1 batch)
#'   
#' @examples
#' 
#' # A BASiCS_Chain object created by the BASiCS_MCMC function.
#' Data <- makeExampleBASiCS_Data()
#' Chain <- BASiCS_MCMC(Data, N = 100, Thin = 2, Burn = 2)
#' 
#' @author Catalina A. Vallejos \email{cnvallej@@uc.cl}
#' 
#' @references 
#' 
#' Vallejos, Marioni and Richardson (2015). PLoS Computational Biology.
#' 
setClass("BASiCS_Chain", 
         representation = representation(mu = "matrix", 
                                         delta = "matrix", 
                                         phi = "matrix", 
                                         s = "matrix", 
                                         nu = "matrix", 
                                         theta = "matrix"), 
         validity = function(object) 
         {
            errors <- character()
            
            if (length(object@mu) == 0 | length(object@delta) == 0 | 
                length(object@phi) == 0 | length(object@s) == 0 | 
                length(object@nu) ==  0 | length(object@theta) == 0) 
            {
              errors <- c(errors, "One or more slots are missing")
              return(errors)
            }
    
          N <- nrow(object@mu)
          n <- ncol(object@phi)
          if (nrow(object@delta) != N | nrow(object@phi) != N | 
              nrow(object@s) != N | nrow(object@nu) != N | 
              nrow(object@theta) != N | 
              ncol(object@mu) != ncol(object@delta) | 
              ncol(object@s) != n | ncol(object@nu) != n) 
          {
            errors <- c(errors, "Slots' dimensions are not compatible")
          }
    
          if (sum(!is.finite(object@mu)) + sum(!is.finite(object@delta)) + 
              sum(!is.finite(object@phi)) + sum(!is.finite(object@s)) + 
              sum(!is.finite(object@nu)) + sum(!is.finite(object@theta))) 
          {
            errors <- c(errors, "Some slots contains NAs or Infinite values")
          }
    
        if (length(errors) == 0) 
          TRUE else errors
      })


#' @name BASiCS_Summary
#' @aliases BASiCS_Summary-class
#' 
#' @title The BASiCS_Summary class
#' 
#' @slot mu Posterior medians (1st column), lower (2nd column) and upper 
#' (3rd column) limits of gene-specific mean expression parameters \eqn{\mu_i}.
#' @slot delta Posterior medians (1st column), lower (2nd column) and upper 
#' (3rd column) limits of gene-specific biological over-dispersion parameters 
#' \eqn{\delta_i}, biological genes only 
#' @slot phi Posterior medians (1st column), lower (2nd column) and upper 
#' (3rd column) limits of cell-specific mRNA content normalisation 
#' parameters \eqn{\phi_j}
#' @slot s Posterior medians (1st column), lower (2nd column) and upper 
#' (3rd column) limits of cell-specific technical normalisation 
#' parameters \eqn{s[j]}
#' @slot nu Posterior medians (1st column), lower (2nd column) and upper 
#' (3rd column) limits of cell-specific random effects \eqn{\nu_j}
#' @slot theta Posterior median (1st column), lower (2nd column) and upper 
#' (3rd column) limits of technical over-dispersion parameter(s) \eqn{\theta} 
#' (each row represents one batch)
#' 
#' @examples
#' 
#' # A BASiCS_Summary object created by the Summary method.
#' Data = makeExampleBASiCS_Data()
#' Chain <- BASiCS_MCMC(Data, N = 100, Thin = 2, Burn = 2)
#' ChainSummary <- Summary(Chain)
#' 
#' @description Container of a summary of a \code{\linkS4class{BASiCS_Chain}} 
#' object. In each slot, first column contains posterior medians; second and 
#' third columns respectively contain the lower and upper limits of an high 
#' posterior density interval (for a given probability).
#' 
setClass("BASiCS_Summary", 
         representation = representation(mu = "matrix", 
                                         delta = "matrix", 
                                         phi = "matrix", 
                                         s = "matrix", 
                                         nu = "matrix", 
                                         theta = "matrix"), 
         validity = function(object) 
        {
          if (sum(!is.finite(object@mu)) > 0 | 
              sum(!is.finite(object@delta)) > 0 | 
              sum(!is.finite(object@phi)) > 0 | 
              sum(!is.finite(object@s)) > 0 | 
              sum(!is.finite(object@nu)) > 0 | 
              sum(!is.finite(object@theta)) > 0) 
                stop("Invalid slots") else { TRUE }
      })
