HiddenBASiCS_MCMC_NoSpikesParam <- function(Counts, ConstrainType, StochasticRef, 
                                            q.bio, mu0, PriorDelta)
{
  if (PriorDelta == "gamma") 
    stop("PriorDelta = 'gamma' is not supported for the no-spikes case")
  
  # 1: Full constrain; 2: Genes with average count >= 1
  if (ConstrainType == 1) {
    ConstrainGene <- (1:q.bio) - 1
    NotConstrainGene <- 0
  }
  if (ConstrainType == 2) {
    ConstrainGene <- which(matrixStats::rowMeans2(Counts) >= 1) - 1
    NotConstrainGene <- which(matrixStats::rowMeans2(Counts) < 1) - 1
  }
  Constrain <- mean(log(mu0[ConstrainGene + 1]))  
  
  # Whether or not a stochatic reference is used
  # If stochastic, range of possible reference values only includes 
  # the nearest 10% genes located around the constrain
  
  if (StochasticRef == TRUE) {
    aux.ref <- cbind(ConstrainGene, 
                     abs(log(mu0[ConstrainGene + 1]) - Constrain))
    aux.ref <- aux.ref[order(aux.ref[, 2]), ]
    # In total 10% of genes to be used as reference candidates
    CandidateRef <- round(0.10 * q.bio)
    # Fix for the code to run on the synthetic small dataset
    # generated by makeExample_BASiCS function (less than 200 genes)
    if(length(ConstrainGene) > CandidateRef) { 
      RefGenes <- aux.ref[seq_len(CandidateRef), 1] 
    } 
    else { RefGenes <- aux.ref[, 1] }
    RefGene <- RefGenes[1]
  } 
  else {
    aux.ref <- which(abs(log(mu0[ConstrainGene + 1]) - Constrain) == 
                       min(abs(log(mu0[ConstrainGene + 1]) - Constrain)))[1]
    RefGene <- ConstrainGene[aux.ref]
    RefGenes <- RefGene
  }
  
  list(ConstrainGene = ConstrainGene, NotConstrainGene = NotConstrainGene, 
       Constrain = Constrain, RefGenes = RefGenes, RefGene = RefGene)
}