# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HiddenBASiCS_MCMCcpp <- function(N, thin, burn, Counts, mu0, delta0, phi0, s0, nu0, theta0, s2mu, adelta, bdelta, p_Phi, as, bs, atheta, btheta, ar, LSmu0, LSdelta0, LSphi0, LSnu0, LStheta0, sumByCellAll, sumByCellBio, sumByGeneAll, sumByGeneBio, StoreAdapt, EndAdapt, PrintProgress, s2_delta, prior_delta) {
    .Call('BASiCS_HiddenBASiCS_MCMCcpp', PACKAGE = 'BASiCS', N, thin, burn, Counts, mu0, delta0, phi0, s0, nu0, theta0, s2mu, adelta, bdelta, p_Phi, as, bs, atheta, btheta, ar, LSmu0, LSdelta0, LSphi0, LSnu0, LStheta0, sumByCellAll, sumByCellBio, sumByGeneAll, sumByGeneBio, StoreAdapt, EndAdapt, PrintProgress, s2_delta, prior_delta)
}

HiddenBASiCS_MCMCcppBatch <- function(N, thin, burn, Counts, BatchDesign, mu0, delta0, phi0, s0, nu0, theta0, s2mu, adelta, bdelta, p_Phi, as, bs, atheta, btheta, ar, LSmu0, LSdelta0, LSphi0, LSnu0, LStheta0, sumByCellAll, sumByCellBio, sumByGeneAll, sumByGeneBio, StoreAdapt, EndAdapt, PrintProgress, s2_delta, prior_delta) {
    .Call('BASiCS_HiddenBASiCS_MCMCcppBatch', PACKAGE = 'BASiCS', N, thin, burn, Counts, BatchDesign, mu0, delta0, phi0, s0, nu0, theta0, s2mu, adelta, bdelta, p_Phi, as, bs, atheta, btheta, ar, LSmu0, LSdelta0, LSphi0, LSnu0, LStheta0, sumByCellAll, sumByCellBio, sumByGeneAll, sumByGeneBio, StoreAdapt, EndAdapt, PrintProgress, s2_delta, prior_delta)
}

HiddenBASiCS_MCMCcppNoSpikes <- function(N, thin, burn, Counts, BatchDesign, mu0, delta0, phi0, nu0, theta0, s2mu, adelta, bdelta, p_Phi, atheta, btheta, ar, LSmu0, LSdelta0, LSphi0, LSnu0, LStheta0, sumByCellAll, sumByGeneAll, StoreAdapt, EndAdapt, PrintProgress, s2_delta, prior_delta, BatchInfo, BatchIds, BatchSizes, BatchOffSet) {
    .Call('BASiCS_HiddenBASiCS_MCMCcppNoSpikes', PACKAGE = 'BASiCS', N, thin, burn, Counts, BatchDesign, mu0, delta0, phi0, nu0, theta0, s2mu, adelta, bdelta, p_Phi, atheta, btheta, ar, LSmu0, LSdelta0, LSphi0, LSnu0, LStheta0, sumByCellAll, sumByGeneAll, StoreAdapt, EndAdapt, PrintProgress, s2_delta, prior_delta, BatchInfo, BatchIds, BatchSizes, BatchOffSet)
}

